### ISSUE TITLE
Get hourly weather data of one month?

### ISSUE THREAD

**Issue by kangjf1943** [uribo/jmastats#2]
Hi, Uribo san, it is me again ... I wonder if there is a way that users can get hourly weather without using apply()-related functions or loop? 
For example, if I want to get the hourly weather data of Jan, 2020, that is what I do: 
```
hour_wx_jan <- list()
for (i in 1:31) {
  hour_wx_jan[[i]] <- 
    jma_collect(item = "hourly", block_no = 47646, year = 2020, month = 1, day = i)
}
hour_wx_jan <- do.call(rbind, hour_wx_jan)
```
or: 
```
hour_wx_jan <- lapply(1:31, function(x) {
  jma_collect(item = "hourly", block_no = 47646, year = 2020, month = 1, day = x)
}) %>% 
  do.call(rbind, .)
```
I wonder if there is a better way to do that? And furthermore, if it is possible to get hourly weather data with a simple magical code (or I will have to use a more complex structure to do that)?

**Comment by uribo** [comment]
No. Only one observatory and time zone can be requested with `jma_collect()` at a time.
However, I feel that there are many cases where you want to obtain data for multiple time periods (for example, hourly values for 24 hours) at once. This process will be considered for future implementation.

**Comment by kangjf1943** [comment]
Got it! Thanks :D
