### ISSUE TITLE
Collecting daily maximum temperature data

### ISSUE THREAD

**Issue by XU159-claire** [uribo/jmastats#22]
I'm sorry, but can this code also be used to obtain daily maximum temperature data? 
because I did not find any key-words I could input to request this kind of data. Or am I missing something? 

Thank you!

**Comment by uribo** [comment]
Yes, this code can be used to get daily maximum temperature data! Just make sure to specify the correct date and block_no for the location you’re interested in.

``` r
# https://www.data.jma.go.jp/stats/etrn/view/daily_s1.php?prec_no=71&block_no=47895&year=2024&month=7&day=7&view=p1
library(jmastats)
jma_collect(item = "daily", block_no = "47895", year = 2024, month = 7, day = 7) |> 
  dplyr::select(temperature) |> 
  tidyr::unnest_wider(col = temperature) |> 
  dplyr::select(2)
#> # A tibble: 31 × 1
#>    `max(℃)`
#>       <dbl>
#>  1     26.5
#>  2     28.5
#>  3     31.2
#>  4     32.6
#>  5     33.3
#>  6     34.3
#>  7     34.1
#>  8     33.3
#>  9     32.6
#> 10     33.6
#> # ℹ 21 more rows
```

<sup>Created on 2024-10-31 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>
Let me know if you need further help!
