### ISSUE TITLE
Track after 2019 are mislabeled as 192x instead of 202x

### ISSUE THREAD

**Issue by drat70** [uribo/jmastats#23]
When importing tracks using read_rsmc_besttrack tracks with dates from 2020 onwards are classified as 1920 onwards instead.

This is probably due to the following lines in track.R:

>  dplyr::if_else(as.numeric(stringr::str_sub(datetime, 1, 2)) <= 19,
>                          "20",
>                          "19"),

It should be safe to change the threshold from 19 to something higher, as the earliest tracks in the datasets are from the 1950s.

**Comment by uribo** [comment]
Thank you for your report, and I’m sorry for the trouble I caused.

As you pointed out, I’ve updated the threshold for the year.
