### ISSUE TITLE
観測所番号：49036のデータ読込み

### ISSUE THREAD

**Issue by kizen777** [uribo/jmastats#24]
使い方説明にあります，47から始まる5桁の番号観測所のデータは入手できるのですが，49から始まる観測所のデータが入手できません。次のエラーが表示されます。
> jma_collect(item = "hourly", block_no = 49036, year = 2022, month = 1, day = 1)
Error in `check_block_no()`:
! The 5-digit block_no must start with '47'.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by uribo** [comment]
観測所番号 station_no と jma_collect()関数で指定するblock_noは異なります。
観測所番号 49036は「大泉」になりますが、その場合のblock_noは1023です。
データ取得対象の観測所が明らかな場合、block_noは以下のように調べられます。

``` r
library(jmastats)
library(dplyr, warn.conflicts = FALSE)
data("stations")

stations |> 
  filter(station_no == "49036") |> 
  pull(block_no)
#> [1] "1023"

# jma_collect(item = "hourly", block_no = 1023, year = 2022, month = 1, day = 1)
```

<sup>Created on 2024-11-25 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by kizen777** [comment]
お忙しい中ありがとうございます。気象データの何が欲しかったかをお知らせしていませんでした。現地気圧，気温，相対湿度です。下記のコードでblock_noを調べて，知りたい地域の最寄りの観測所のblock_noを{jmastats}で入手できるようになりました。ありがとうございます。
このblock_noで調べた時には，欲しいデータが入手できなかったので，私のRコーディングが待ちがっていたと思っていました。そこで次のコードで47から始まる47XXX５桁のstation_typeを表示させたところ，"官"とありました。旧称測候所と呼ばれたところらしい（大阪管区気象庁の方談）とのことで，ここでは現地気圧も測定していることでした（再出〜の方）。
気象庁のサイトにありました，https://www.metds.co.jp/wp-content/uploads/2023/01/EA_fundamental_2020_221231.pdf資料をみましても，実のところよくわかりません。ご機会があれば，現地気圧を測量している観測所の見分け方教えていただければ幸いです。
# 必要なパッケージの読み込み
library(jmastats)
library(dplyr, warn.conflicts = FALSE)

# stationsデータの読み込み（jmastatsパッケージに含まれるデータ）
data("stations")

# station_dataから特定の範囲のblock_noを持つ観測所を抽出
stations_subset <- stations %>%
  filter(as.numeric(block_no) >= 47000 & as.numeric(block_no) <= 47999) %>%
  select(station_no, station_type, station_name, block_no, area, address) %>%
  arrange(as.numeric(block_no))

# 結果を表示
print(stations_subset, n = Inf)  # 全ての結果を表示
